/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class datapath_NodePuppet */

#ifndef _Included_datapath_NodePuppet
#define _Included_datapath_NodePuppet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     datapath_NodePuppet
 * Method:    ProgramNode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_datapath_NodePuppet_ProgramNode
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jstring, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
